[2022-12-03 15:08:36,328] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.get_last_id scheduled__2022-11-28T19:36:00+00:00 [queued]>
[2022-12-03 15:08:37,424] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.get_last_id scheduled__2022-11-28T19:36:00+00:00 [queued]>
[2022-12-03 15:08:37,424] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-03 15:08:37,424] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-03 15:08:37,424] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-03 15:08:37,979] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_last_id> on 2022-11-28 19:36:00+00:00
[2022-12-03 15:08:38,118] {standard_task_runner.py:52} INFO - Started process 1163 to run task
[2022-12-03 15:08:38,227] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'get_last_id', 'scheduled__2022-11-28T19:36:00+00:00', '--job-id', '357', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmp5ju17pfe', '--error-file', '/tmp/tmpyoi9udzr']
[2022-12-03 15:08:38,274] {standard_task_runner.py:80} INFO - Job 357: Subtask get_last_id
[2022-12-03 15:08:40,550] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.get_last_id scheduled__2022-11-28T19:36:00+00:00 [running]> on host b41792e8e843
[2022-12-03 15:08:46,553] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=get_last_id
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T19:36:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T19:36:00+00:00
[2022-12-03 15:08:47,496] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-03 15:08:48,703] {python.py:173} INFO - Done. Returned value was: None
[2022-12-03 15:08:50,529] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=get_last_id, execution_date=20221128T193600, start_date=20221203T150836, end_date=20221203T150850
[2022-12-03 15:08:51,474] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-12-03 15:08:51,628] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 1163. PIDs of all processes in the group: [1163]
[2022-12-03 15:08:51,678] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 1163
[2022-12-03 15:08:51,686] {process_utils.py:75} INFO - Process psutil.Process(pid=1163, status='terminated', exitcode=0, started='15:08:37') (1163) terminated with exit code 0
